import type { Metadata } from "next";
import { Fira_Sans, Roboto } from "next/font/google";
import "./globals.css";

const firaSansFont = Fira_Sans({
  weight: "400",
  variable: "--font-fira-sans",
  subsets: ["cyrillic"],
});

const robotoFont = Roboto({
  weight: "400",
  variable: "--font-roboto",
  subsets: ["cyrillic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${firaSansFont.variable} ${robotoFont.variable}`}>
        {children}
      </body>
    </html>
  );
}
